//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.28 at 03:40:37 PM UTC 
//


package org.bsharp.pubmed.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bsharp.pubmed.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AbstractText_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "AbstractText");
    private final static QName _AccessionNumber_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "AccessionNumber");
    private final static QName _Acronym_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Acronym");
    private final static QName _Affiliation_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Affiliation");
    private final static QName _Agency_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Agency");
    private final static QName _ArticleTitle_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "ArticleTitle");
    private final static QName _CitationSubset_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "CitationSubset");
    private final static QName _CollectiveName_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "CollectiveName");
    private final static QName _CopyrightInformation_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "CopyrightInformation");
    private final static QName _Country_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Country");
    private final static QName _DataBankName_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "DataBankName");
    private final static QName _Day_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Day");
    private final static QName _EndPage_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "EndPage");
    private final static QName _ForeName_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "ForeName");
    private final static QName _GeneSymbol_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "GeneSymbol");
    private final static QName _GrantID_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "GrantID");
    private final static QName _Hour_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Hour");
    private final static QName _ISOAbbreviation_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "ISOAbbreviation");
    private final static QName _ISSNLinking_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "ISSNLinking");
    private final static QName _Initials_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Initials");
    private final static QName _Issue_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Issue");
    private final static QName _Language_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Language");
    private final static QName _LastName_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "LastName");
    private final static QName _MedlineDate_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "MedlineDate");
    private final static QName _MedlinePgn_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "MedlinePgn");
    private final static QName _MedlineTA_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "MedlineTA");
    private final static QName _Minute_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Minute");
    private final static QName _Month_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Month");
    private final static QName _NameOfSubstance_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "NameOfSubstance");
    private final static QName _NlmUniqueID_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "NlmUniqueID");
    private final static QName _Note_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Note");
    private final static QName _NumberOfReferences_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "NumberOfReferences");
    private final static QName _PMID_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "PMID");
    private final static QName _PublicationStatus_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "PublicationStatus");
    private final static QName _PublicationType_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "PublicationType");
    private final static QName _RefSource_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "RefSource");
    private final static QName _RegistryNumber_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "RegistryNumber");
    private final static QName _Season_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Season");
    private final static QName _Second_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Second");
    private final static QName _SpaceFlightMission_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "SpaceFlightMission");
    private final static QName _StartPage_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "StartPage");
    private final static QName _Suffix_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Suffix");
    private final static QName _Title_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Title");
    private final static QName _VernacularTitle_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "VernacularTitle");
    private final static QName _Volume_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Volume");
    private final static QName _Year_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "Year");
    private final static QName _AuthorTypeNameID_QNAME = new QName("http://www.ncbi.nlm.nih.gov/eutils", "NameID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bsharp.pubmed.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MedlineCitationSet }
     * 
     */
    public MedlineCitationSet createMedlineCitationSet() {
        return new MedlineCitationSet();
    }

    /**
     * Create an instance of {@link MedlineCitationType }
     * 
     */
    public MedlineCitationType createMedlineCitationType() {
        return new MedlineCitationType();
    }

    /**
     * Create an instance of {@link DeleteCitationType }
     * 
     */
    public DeleteCitationType createDeleteCitationType() {
        return new DeleteCitationType();
    }

    /**
     * Create an instance of {@link PubmedArticleSet }
     * 
     */
    public PubmedArticleSet createPubmedArticleSet() {
        return new PubmedArticleSet();
    }

    /**
     * Create an instance of {@link PubmedArticleType }
     * 
     */
    public PubmedArticleType createPubmedArticleType() {
        return new PubmedArticleType();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link AbstractType }
     * 
     */
    public AbstractType createAbstractType() {
        return new AbstractType();
    }

    /**
     * Create an instance of {@link AccessionNumberListType }
     * 
     */
    public AccessionNumberListType createAccessionNumberListType() {
        return new AccessionNumberListType();
    }

    /**
     * Create an instance of {@link ArticleType }
     * 
     */
    public ArticleType createArticleType() {
        return new ArticleType();
    }

    /**
     * Create an instance of {@link ArticleDateType }
     * 
     */
    public ArticleDateType createArticleDateType() {
        return new ArticleDateType();
    }

    /**
     * Create an instance of {@link ArticleIdType }
     * 
     */
    public ArticleIdType createArticleIdType() {
        return new ArticleIdType();
    }

    /**
     * Create an instance of {@link ArticleIdListType }
     * 
     */
    public ArticleIdListType createArticleIdListType() {
        return new ArticleIdListType();
    }

    /**
     * Create an instance of {@link AuthorType }
     * 
     */
    public AuthorType createAuthorType() {
        return new AuthorType();
    }

    /**
     * Create an instance of {@link AuthorListType }
     * 
     */
    public AuthorListType createAuthorListType() {
        return new AuthorListType();
    }

    /**
     * Create an instance of {@link ChemicalType }
     * 
     */
    public ChemicalType createChemicalType() {
        return new ChemicalType();
    }

    /**
     * Create an instance of {@link ChemicalListType }
     * 
     */
    public ChemicalListType createChemicalListType() {
        return new ChemicalListType();
    }

    /**
     * Create an instance of {@link CommentsCorrectionsType }
     * 
     */
    public CommentsCorrectionsType createCommentsCorrectionsType() {
        return new CommentsCorrectionsType();
    }

    /**
     * Create an instance of {@link CommentsCorrectionsListType }
     * 
     */
    public CommentsCorrectionsListType createCommentsCorrectionsListType() {
        return new CommentsCorrectionsListType();
    }

    /**
     * Create an instance of {@link DataBankType }
     * 
     */
    public DataBankType createDataBankType() {
        return new DataBankType();
    }

    /**
     * Create an instance of {@link DataBankListType }
     * 
     */
    public DataBankListType createDataBankListType() {
        return new DataBankListType();
    }

    /**
     * Create an instance of {@link DateCompletedType }
     * 
     */
    public DateCompletedType createDateCompletedType() {
        return new DateCompletedType();
    }

    /**
     * Create an instance of {@link DateCreatedType }
     * 
     */
    public DateCreatedType createDateCreatedType() {
        return new DateCreatedType();
    }

    /**
     * Create an instance of {@link DateRevisedType }
     * 
     */
    public DateRevisedType createDateRevisedType() {
        return new DateRevisedType();
    }

    /**
     * Create an instance of {@link DescriptorNameType }
     * 
     */
    public DescriptorNameType createDescriptorNameType() {
        return new DescriptorNameType();
    }

    /**
     * Create an instance of {@link ELocationIDType }
     * 
     */
    public ELocationIDType createELocationIDType() {
        return new ELocationIDType();
    }

    /**
     * Create an instance of {@link GeneSymbolListType }
     * 
     */
    public GeneSymbolListType createGeneSymbolListType() {
        return new GeneSymbolListType();
    }

    /**
     * Create an instance of {@link GeneralNoteType }
     * 
     */
    public GeneralNoteType createGeneralNoteType() {
        return new GeneralNoteType();
    }

    /**
     * Create an instance of {@link GrantType }
     * 
     */
    public GrantType createGrantType() {
        return new GrantType();
    }

    /**
     * Create an instance of {@link GrantListType }
     * 
     */
    public GrantListType createGrantListType() {
        return new GrantListType();
    }

    /**
     * Create an instance of {@link HistoryType }
     * 
     */
    public HistoryType createHistoryType() {
        return new HistoryType();
    }

    /**
     * Create an instance of {@link ISSNType }
     * 
     */
    public ISSNType createISSNType() {
        return new ISSNType();
    }

    /**
     * Create an instance of {@link InvestigatorType }
     * 
     */
    public InvestigatorType createInvestigatorType() {
        return new InvestigatorType();
    }

    /**
     * Create an instance of {@link InvestigatorListType }
     * 
     */
    public InvestigatorListType createInvestigatorListType() {
        return new InvestigatorListType();
    }

    /**
     * Create an instance of {@link JournalType }
     * 
     */
    public JournalType createJournalType() {
        return new JournalType();
    }

    /**
     * Create an instance of {@link JournalIssueType }
     * 
     */
    public JournalIssueType createJournalIssueType() {
        return new JournalIssueType();
    }

    /**
     * Create an instance of {@link KeywordType }
     * 
     */
    public KeywordType createKeywordType() {
        return new KeywordType();
    }

    /**
     * Create an instance of {@link KeywordListType }
     * 
     */
    public KeywordListType createKeywordListType() {
        return new KeywordListType();
    }

    /**
     * Create an instance of {@link MedlineJournalInfoType }
     * 
     */
    public MedlineJournalInfoType createMedlineJournalInfoType() {
        return new MedlineJournalInfoType();
    }

    /**
     * Create an instance of {@link MeshHeadingType }
     * 
     */
    public MeshHeadingType createMeshHeadingType() {
        return new MeshHeadingType();
    }

    /**
     * Create an instance of {@link MeshHeadingListType }
     * 
     */
    public MeshHeadingListType createMeshHeadingListType() {
        return new MeshHeadingListType();
    }

    /**
     * Create an instance of {@link NameIDType }
     * 
     */
    public NameIDType createNameIDType() {
        return new NameIDType();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link ObjectListType }
     * 
     */
    public ObjectListType createObjectListType() {
        return new ObjectListType();
    }

    /**
     * Create an instance of {@link OtherAbstractType }
     * 
     */
    public OtherAbstractType createOtherAbstractType() {
        return new OtherAbstractType();
    }

    /**
     * Create an instance of {@link OtherIDType }
     * 
     */
    public OtherIDType createOtherIDType() {
        return new OtherIDType();
    }

    /**
     * Create an instance of {@link PaginationType }
     * 
     */
    public PaginationType createPaginationType() {
        return new PaginationType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link PersonalNameSubjectType }
     * 
     */
    public PersonalNameSubjectType createPersonalNameSubjectType() {
        return new PersonalNameSubjectType();
    }

    /**
     * Create an instance of {@link PersonalNameSubjectListType }
     * 
     */
    public PersonalNameSubjectListType createPersonalNameSubjectListType() {
        return new PersonalNameSubjectListType();
    }

    /**
     * Create an instance of {@link PubDateType }
     * 
     */
    public PubDateType createPubDateType() {
        return new PubDateType();
    }

    /**
     * Create an instance of {@link PubMedPubDateType }
     * 
     */
    public PubMedPubDateType createPubMedPubDateType() {
        return new PubMedPubDateType();
    }

    /**
     * Create an instance of {@link PublicationTypeListType }
     * 
     */
    public PublicationTypeListType createPublicationTypeListType() {
        return new PublicationTypeListType();
    }

    /**
     * Create an instance of {@link PubmedDataType }
     * 
     */
    public PubmedDataType createPubmedDataType() {
        return new PubmedDataType();
    }

    /**
     * Create an instance of {@link QualifierNameType }
     * 
     */
    public QualifierNameType createQualifierNameType() {
        return new QualifierNameType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "AbstractText")
    public JAXBElement<String> createAbstractText(String value) {
        return new JAXBElement<String>(_AbstractText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "AccessionNumber")
    public JAXBElement<String> createAccessionNumber(String value) {
        return new JAXBElement<String>(_AccessionNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Acronym")
    public JAXBElement<String> createAcronym(String value) {
        return new JAXBElement<String>(_Acronym_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Affiliation")
    public JAXBElement<String> createAffiliation(String value) {
        return new JAXBElement<String>(_Affiliation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Agency")
    public JAXBElement<String> createAgency(String value) {
        return new JAXBElement<String>(_Agency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "ArticleTitle")
    public JAXBElement<String> createArticleTitle(String value) {
        return new JAXBElement<String>(_ArticleTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "CitationSubset")
    public JAXBElement<String> createCitationSubset(String value) {
        return new JAXBElement<String>(_CitationSubset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "CollectiveName")
    public JAXBElement<String> createCollectiveName(String value) {
        return new JAXBElement<String>(_CollectiveName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "CopyrightInformation")
    public JAXBElement<String> createCopyrightInformation(String value) {
        return new JAXBElement<String>(_CopyrightInformation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "DataBankName")
    public JAXBElement<String> createDataBankName(String value) {
        return new JAXBElement<String>(_DataBankName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Day")
    public JAXBElement<String> createDay(String value) {
        return new JAXBElement<String>(_Day_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "EndPage")
    public JAXBElement<String> createEndPage(String value) {
        return new JAXBElement<String>(_EndPage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "ForeName")
    public JAXBElement<String> createForeName(String value) {
        return new JAXBElement<String>(_ForeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "GeneSymbol")
    public JAXBElement<String> createGeneSymbol(String value) {
        return new JAXBElement<String>(_GeneSymbol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "GrantID")
    public JAXBElement<String> createGrantID(String value) {
        return new JAXBElement<String>(_GrantID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Hour")
    public JAXBElement<String> createHour(String value) {
        return new JAXBElement<String>(_Hour_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "ISOAbbreviation")
    public JAXBElement<String> createISOAbbreviation(String value) {
        return new JAXBElement<String>(_ISOAbbreviation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "ISSNLinking")
    public JAXBElement<String> createISSNLinking(String value) {
        return new JAXBElement<String>(_ISSNLinking_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Initials")
    public JAXBElement<String> createInitials(String value) {
        return new JAXBElement<String>(_Initials_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Issue")
    public JAXBElement<String> createIssue(String value) {
        return new JAXBElement<String>(_Issue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Language")
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "LastName")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "MedlineDate")
    public JAXBElement<String> createMedlineDate(String value) {
        return new JAXBElement<String>(_MedlineDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "MedlinePgn")
    public JAXBElement<String> createMedlinePgn(String value) {
        return new JAXBElement<String>(_MedlinePgn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "MedlineTA")
    public JAXBElement<String> createMedlineTA(String value) {
        return new JAXBElement<String>(_MedlineTA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Minute")
    public JAXBElement<String> createMinute(String value) {
        return new JAXBElement<String>(_Minute_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Month")
    public JAXBElement<String> createMonth(String value) {
        return new JAXBElement<String>(_Month_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "NameOfSubstance")
    public JAXBElement<String> createNameOfSubstance(String value) {
        return new JAXBElement<String>(_NameOfSubstance_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "NlmUniqueID")
    public JAXBElement<String> createNlmUniqueID(String value) {
        return new JAXBElement<String>(_NlmUniqueID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Note")
    public JAXBElement<String> createNote(String value) {
        return new JAXBElement<String>(_Note_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "NumberOfReferences")
    public JAXBElement<String> createNumberOfReferences(String value) {
        return new JAXBElement<String>(_NumberOfReferences_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "PMID")
    public JAXBElement<String> createPMID(String value) {
        return new JAXBElement<String>(_PMID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "PublicationStatus")
    public JAXBElement<String> createPublicationStatus(String value) {
        return new JAXBElement<String>(_PublicationStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "PublicationType")
    public JAXBElement<String> createPublicationType(String value) {
        return new JAXBElement<String>(_PublicationType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "RefSource")
    public JAXBElement<String> createRefSource(String value) {
        return new JAXBElement<String>(_RefSource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "RegistryNumber")
    public JAXBElement<String> createRegistryNumber(String value) {
        return new JAXBElement<String>(_RegistryNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Season")
    public JAXBElement<String> createSeason(String value) {
        return new JAXBElement<String>(_Season_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Second")
    public JAXBElement<String> createSecond(String value) {
        return new JAXBElement<String>(_Second_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "SpaceFlightMission")
    public JAXBElement<String> createSpaceFlightMission(String value) {
        return new JAXBElement<String>(_SpaceFlightMission_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "StartPage")
    public JAXBElement<String> createStartPage(String value) {
        return new JAXBElement<String>(_StartPage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Suffix")
    public JAXBElement<String> createSuffix(String value) {
        return new JAXBElement<String>(_Suffix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "VernacularTitle")
    public JAXBElement<String> createVernacularTitle(String value) {
        return new JAXBElement<String>(_VernacularTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Volume")
    public JAXBElement<String> createVolume(String value) {
        return new JAXBElement<String>(_Volume_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "Year")
    public JAXBElement<String> createYear(String value) {
        return new JAXBElement<String>(_Year_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameIDType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NameIDType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ncbi.nlm.nih.gov/eutils", name = "NameID", scope = AuthorType.class)
    public JAXBElement<NameIDType> createAuthorTypeNameID(NameIDType value) {
        return new JAXBElement<NameIDType>(_AuthorTypeNameID_QNAME, NameIDType.class, AuthorType.class, value);
    }

}
