#!/bin/sh
## the javax.xml.accessExternalDTD property must be set to https!
java -Djavax.xml.accessExternalDTD=https -cp "build/install/bsharp-pubmed/lib/*" org.bsharp.pubmed.Abstract $1 $2 $PUBMED_API_KEY
